# Build stage
FROM golang:1.25-alpine AS build

# Set working directory
WORKDIR /app

# Copy dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the worker application
RUN CGO_ENABLED=0 go build -o /worker-service ./cmd/worker-service/main.go

# Final stage
FROM scratch

# Copy binary from build stage
COPY --from=build /worker-service /worker-service

# Expose metrics port
EXPOSE 8081

# Start the worker application
ENTRYPOINT ["/worker-service"]