# --- Build Stage ---
FROM golang:1.25-alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the worker-service binary
RUN CGO_ENABLED=0 go build -o /worker-service ./cmd/worker-service/main.go

# --- Final Stage ---
FROM scratch

# Copy the binary from the 'build' stage
COPY --from=build /worker-service /worker-service

# Expose the metrics port
EXPOSE 8081

# Command to run
ENTRYPOINT ["/worker-service"]